CREATE TABLE m_ego_suit
(pri_key int PRIMARY KEY NOT NULL, 
risk_level integer,
cost text, 
capacity integer,
name_en text,
name_ja text,
red_resist integer,
white_resist integer,
black_resist integer,
pale_resist integer,
equip_remarks text,
skill_remarks text,
name_key text,
abnoma_url text)