# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './forms/set_work_apetitude_form.ui'
#
# Created: Sun Oct 14 13:32:32 2018
#      by: pyside2-uic 2.0.0 running on PySide2 5.6.0~a1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_SetWorkApetitudeForm(object):
    def setupUi(self, SetWorkApetitudeForm):
        SetWorkApetitudeForm.setObjectName("SetWorkApetitudeForm")
        SetWorkApetitudeForm.resize(382, 279)
        self.horizontalLayoutWidget = QtWidgets.QWidget(SetWorkApetitudeForm)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 361, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lblAbnormality = QtWidgets.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAbnormality.sizePolicy().hasHeightForWidth())
        self.lblAbnormality.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(12)
        self.lblAbnormality.setFont(font)
        self.lblAbnormality.setObjectName("lblAbnormality")
        self.horizontalLayout.addWidget(self.lblAbnormality)
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.horizontalLayout.setStretch(1, 1)
        self.lblAbnormality_2 = QtWidgets.QLabel(SetWorkApetitudeForm)
        self.lblAbnormality_2.setGeometry(QtCore.QRect(20, 70, 113, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAbnormality_2.sizePolicy().hasHeightForWidth())
        self.lblAbnormality_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        self.lblAbnormality_2.setFont(font)
        self.lblAbnormality_2.setObjectName("lblAbnormality_2")
        self.lblAbnormality_3 = QtWidgets.QLabel(SetWorkApetitudeForm)
        self.lblAbnormality_3.setGeometry(QtCore.QRect(20, 110, 113, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAbnormality_3.sizePolicy().hasHeightForWidth())
        self.lblAbnormality_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        self.lblAbnormality_3.setFont(font)
        self.lblAbnormality_3.setObjectName("lblAbnormality_3")
        self.lblAbnormality_4 = QtWidgets.QLabel(SetWorkApetitudeForm)
        self.lblAbnormality_4.setGeometry(QtCore.QRect(20, 150, 113, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAbnormality_4.sizePolicy().hasHeightForWidth())
        self.lblAbnormality_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        self.lblAbnormality_4.setFont(font)
        self.lblAbnormality_4.setObjectName("lblAbnormality_4")
        self.lblAbnormality_5 = QtWidgets.QLabel(SetWorkApetitudeForm)
        self.lblAbnormality_5.setGeometry(QtCore.QRect(20, 190, 113, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAbnormality_5.sizePolicy().hasHeightForWidth())
        self.lblAbnormality_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        self.lblAbnormality_5.setFont(font)
        self.lblAbnormality_5.setObjectName("lblAbnormality_5")
        self.cmbInst = QtWidgets.QComboBox(SetWorkApetitudeForm)
        self.cmbInst.setGeometry(QtCore.QRect(80, 70, 261, 31))
        self.cmbInst.setObjectName("cmbInst")
        self.cmbInsi = QtWidgets.QComboBox(SetWorkApetitudeForm)
        self.cmbInsi.setGeometry(QtCore.QRect(80, 110, 261, 31))
        self.cmbInsi.setObjectName("cmbInsi")
        self.cmbAtta = QtWidgets.QComboBox(SetWorkApetitudeForm)
        self.cmbAtta.setGeometry(QtCore.QRect(80, 150, 261, 31))
        self.cmbAtta.setObjectName("cmbAtta")
        self.cmbSupr = QtWidgets.QComboBox(SetWorkApetitudeForm)
        self.cmbSupr.setGeometry(QtCore.QRect(80, 190, 261, 31))
        self.cmbSupr.setObjectName("cmbSupr")
        self.pushButton = QtWidgets.QPushButton(SetWorkApetitudeForm)
        self.pushButton.setGeometry(QtCore.QRect(280, 240, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(SetWorkApetitudeForm)
        QtCore.QObject.connect(self.pushButton, QtCore.SIGNAL("clicked()"), SetWorkApetitudeForm.btnOK_clicked)
        QtCore.QMetaObject.connectSlotsByName(SetWorkApetitudeForm)

    def retranslateUi(self, SetWorkApetitudeForm):
        SetWorkApetitudeForm.setWindowTitle(QtWidgets.QApplication.translate("SetWorkApetitudeForm", "Dialog", None, -1))
        self.lblAbnormality.setText(QtWidgets.QApplication.translate("SetWorkApetitudeForm", "アブノーマリティ", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("SetWorkApetitudeForm", "の作業適性", None, -1))
        self.lblAbnormality_2.setText(QtWidgets.QApplication.translate("SetWorkApetitudeForm", "本能", None, -1))
        self.lblAbnormality_3.setText(QtWidgets.QApplication.translate("SetWorkApetitudeForm", "洞察", None, -1))
        self.lblAbnormality_4.setText(QtWidgets.QApplication.translate("SetWorkApetitudeForm", "愛着", None, -1))
        self.lblAbnormality_5.setText(QtWidgets.QApplication.translate("SetWorkApetitudeForm", "抑圧", None, -1))
        self.pushButton.setText(QtWidgets.QApplication.translate("SetWorkApetitudeForm", "OK", None, -1))

