# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './forms/team_form.ui'
#
# Created: Tue Nov 20 00:02:37 2018
#      by: pyside2-uic 2.0.0 running on PySide2 5.6.0~a1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_TeamForm(object):
    def setupUi(self, TeamForm):
        TeamForm.setObjectName("TeamForm")
        TeamForm.resize(766, 906)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        TeamForm.setFont(font)
        self.btnInstinct = QtWidgets.QPushButton(TeamForm)
        self.btnInstinct.setGeometry(QtCore.QRect(800, 70, 41, 41))
        self.btnInstinct.setObjectName("btnInstinct")
        self.imgControl = QtWidgets.QLabel(TeamForm)
        self.imgControl.setGeometry(QtCore.QRect(280, 40, 50, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imgControl.sizePolicy().hasHeightForWidth())
        self.imgControl.setSizePolicy(sizePolicy)
        self.imgControl.setMinimumSize(QtCore.QSize(20, 20))
        self.imgControl.setObjectName("imgControl")
        self.imgSafe = QtWidgets.QLabel(TeamForm)
        self.imgSafe.setGeometry(QtCore.QRect(30, 170, 50, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imgSafe.sizePolicy().hasHeightForWidth())
        self.imgSafe.setSizePolicy(sizePolicy)
        self.imgSafe.setMinimumSize(QtCore.QSize(20, 20))
        self.imgSafe.setObjectName("imgSafe")
        self.imgInfo = QtWidgets.QLabel(TeamForm)
        self.imgInfo.setGeometry(QtCore.QRect(280, 170, 50, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imgInfo.sizePolicy().hasHeightForWidth())
        self.imgInfo.setSizePolicy(sizePolicy)
        self.imgInfo.setMinimumSize(QtCore.QSize(20, 20))
        self.imgInfo.setObjectName("imgInfo")
        self.imgTrain = QtWidgets.QLabel(TeamForm)
        self.imgTrain.setGeometry(QtCore.QRect(530, 170, 50, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imgTrain.sizePolicy().hasHeightForWidth())
        self.imgTrain.setSizePolicy(sizePolicy)
        self.imgTrain.setMinimumSize(QtCore.QSize(20, 20))
        self.imgTrain.setObjectName("imgTrain")
        self.imgCenter1 = QtWidgets.QLabel(TeamForm)
        self.imgCenter1.setGeometry(QtCore.QRect(280, 320, 50, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imgCenter1.sizePolicy().hasHeightForWidth())
        self.imgCenter1.setSizePolicy(sizePolicy)
        self.imgCenter1.setMinimumSize(QtCore.QSize(20, 20))
        self.imgCenter1.setObjectName("imgCenter1")
        self.imgWelfare = QtWidgets.QLabel(TeamForm)
        self.imgWelfare.setGeometry(QtCore.QRect(30, 450, 50, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imgWelfare.sizePolicy().hasHeightForWidth())
        self.imgWelfare.setSizePolicy(sizePolicy)
        self.imgWelfare.setMinimumSize(QtCore.QSize(20, 20))
        self.imgWelfare.setObjectName("imgWelfare")
        self.imgPanish = QtWidgets.QLabel(TeamForm)
        self.imgPanish.setGeometry(QtCore.QRect(530, 450, 50, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imgPanish.sizePolicy().hasHeightForWidth())
        self.imgPanish.setSizePolicy(sizePolicy)
        self.imgPanish.setMinimumSize(QtCore.QSize(20, 20))
        self.imgPanish.setObjectName("imgPanish")
        self.imgMemory = QtWidgets.QLabel(TeamForm)
        self.imgMemory.setGeometry(QtCore.QRect(30, 620, 50, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imgMemory.sizePolicy().hasHeightForWidth())
        self.imgMemory.setSizePolicy(sizePolicy)
        self.imgMemory.setMinimumSize(QtCore.QSize(20, 20))
        self.imgMemory.setObjectName("imgMemory")
        self.imgExtract = QtWidgets.QLabel(TeamForm)
        self.imgExtract.setGeometry(QtCore.QRect(530, 620, 50, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imgExtract.sizePolicy().hasHeightForWidth())
        self.imgExtract.setSizePolicy(sizePolicy)
        self.imgExtract.setMinimumSize(QtCore.QSize(20, 20))
        self.imgExtract.setObjectName("imgExtract")
        self.btnInsight = QtWidgets.QPushButton(TeamForm)
        self.btnInsight.setGeometry(QtCore.QRect(840, 70, 41, 41))
        self.btnInsight.setObjectName("btnInsight")
        self.btnAttachment = QtWidgets.QPushButton(TeamForm)
        self.btnAttachment.setGeometry(QtCore.QRect(800, 110, 41, 41))
        self.btnAttachment.setObjectName("btnAttachment")
        self.btnSuppression = QtWidgets.QPushButton(TeamForm)
        self.btnSuppression.setGeometry(QtCore.QRect(840, 110, 41, 41))
        self.btnSuppression.setObjectName("btnSuppression")
        self.btnClear = QtWidgets.QPushButton(TeamForm)
        self.btnClear.setEnabled(True)
        self.btnClear.setGeometry(QtCore.QRect(1040, 40, 111, 31))
        self.btnClear.setObjectName("btnClear")
        self.imgAbnoma = QtWidgets.QLabel(TeamForm)
        self.imgAbnoma.setGeometry(QtCore.QRect(40, 40, 50, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imgAbnoma.sizePolicy().hasHeightForWidth())
        self.imgAbnoma.setSizePolicy(sizePolicy)
        self.imgAbnoma.setMinimumSize(QtCore.QSize(20, 20))
        self.imgAbnoma.setObjectName("imgAbnoma")
        self.btnRegister = QtWidgets.QPushButton(TeamForm)
        self.btnRegister.setGeometry(QtCore.QRect(40, 90, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(8)
        self.btnRegister.setFont(font)
        self.btnRegister.setObjectName("btnRegister")
        self.imgSelected = QtWidgets.QLabel(TeamForm)
        self.imgSelected.setGeometry(QtCore.QRect(40, 40, 51, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imgSelected.sizePolicy().hasHeightForWidth())
        self.imgSelected.setSizePolicy(sizePolicy)
        self.imgSelected.setMinimumSize(QtCore.QSize(20, 20))
        self.imgSelected.setObjectName("imgSelected")
        self.imgStared = QtWidgets.QLabel(TeamForm)
        self.imgStared.setGeometry(QtCore.QRect(40, 40, 51, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imgStared.sizePolicy().hasHeightForWidth())
        self.imgStared.setSizePolicy(sizePolicy)
        self.imgStared.setMinimumSize(QtCore.QSize(20, 20))
        self.imgStared.setObjectName("imgStared")
        self.btnStar = QtWidgets.QPushButton(TeamForm)
        self.btnStar.setGeometry(QtCore.QRect(40, 20, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(8)
        self.btnStar.setFont(font)
        self.btnStar.setObjectName("btnStar")
        self.imgCenter2 = QtWidgets.QLabel(TeamForm)
        self.imgCenter2.setGeometry(QtCore.QRect(280, 450, 50, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imgCenter2.sizePolicy().hasHeightForWidth())
        self.imgCenter2.setSizePolicy(sizePolicy)
        self.imgCenter2.setMinimumSize(QtCore.QSize(20, 20))
        self.imgCenter2.setObjectName("imgCenter2")
        self.btnAptitude = QtWidgets.QPushButton(TeamForm)
        self.btnAptitude.setGeometry(QtCore.QRect(120, 30, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        self.btnAptitude.setFont(font)
        self.btnAptitude.setObjectName("btnAptitude")
        self.ledEmployee = QtWidgets.QLineEdit(TeamForm)
        self.ledEmployee.setGeometry(QtCore.QRect(800, 40, 241, 31))
        self.ledEmployee.setObjectName("ledEmployee")
        self.txtAbnoma = QtWidgets.QPlainTextEdit(TeamForm)
        self.txtAbnoma.setGeometry(QtCore.QRect(880, 70, 271, 51))
        self.txtAbnoma.setObjectName("txtAbnoma")
        self.btnResult = QtWidgets.QPushButton(TeamForm)
        self.btnResult.setGeometry(QtCore.QRect(1440, 840, 151, 61))
        self.btnResult.setObjectName("btnResult")

        self.retranslateUi(TeamForm)
        QtCore.QObject.connect(self.btnAptitude, QtCore.SIGNAL("clicked()"), TeamForm.btnAptitude_clicked)
        QtCore.QMetaObject.connectSlotsByName(TeamForm)

    def retranslateUi(self, TeamForm):
        TeamForm.setWindowTitle(QtWidgets.QApplication.translate("TeamForm", "アブノーマリティ", None, -1))
        self.btnInstinct.setText(QtWidgets.QApplication.translate("TeamForm", "本能", None, -1))
        self.imgControl.setText(QtWidgets.QApplication.translate("TeamForm", "TextLabel", None, -1))
        self.imgSafe.setText(QtWidgets.QApplication.translate("TeamForm", "TextLabel", None, -1))
        self.imgInfo.setText(QtWidgets.QApplication.translate("TeamForm", "TextLabel", None, -1))
        self.imgTrain.setText(QtWidgets.QApplication.translate("TeamForm", "TextLabel", None, -1))
        self.imgCenter1.setText(QtWidgets.QApplication.translate("TeamForm", "TextLabel", None, -1))
        self.imgWelfare.setText(QtWidgets.QApplication.translate("TeamForm", "TextLabel", None, -1))
        self.imgPanish.setText(QtWidgets.QApplication.translate("TeamForm", "TextLabel", None, -1))
        self.imgMemory.setText(QtWidgets.QApplication.translate("TeamForm", "TextLabel", None, -1))
        self.imgExtract.setText(QtWidgets.QApplication.translate("TeamForm", "TextLabel", None, -1))
        self.btnInsight.setText(QtWidgets.QApplication.translate("TeamForm", "洞察", None, -1))
        self.btnAttachment.setText(QtWidgets.QApplication.translate("TeamForm", "愛着", None, -1))
        self.btnSuppression.setText(QtWidgets.QApplication.translate("TeamForm", "抑圧", None, -1))
        self.btnClear.setText(QtWidgets.QApplication.translate("TeamForm", "削除", None, -1))
        self.imgAbnoma.setText(QtWidgets.QApplication.translate("TeamForm", "TextLabel", None, -1))
        self.btnRegister.setText(QtWidgets.QApplication.translate("TeamForm", "登録", None, -1))
        self.imgSelected.setText(QtWidgets.QApplication.translate("TeamForm", "TextLabel", None, -1))
        self.imgStared.setText(QtWidgets.QApplication.translate("TeamForm", "TextLabel", None, -1))
        self.btnStar.setText(QtWidgets.QApplication.translate("TeamForm", "★", None, -1))
        self.imgCenter2.setText(QtWidgets.QApplication.translate("TeamForm", "TextLabel", None, -1))
        self.btnAptitude.setText(QtWidgets.QApplication.translate("TeamForm", "作業適性登録", None, -1))
        self.btnResult.setText(QtWidgets.QApplication.translate("TeamForm", "テキスト生成", None, -1))

